# Generated by Django 2.2.7 on 2019-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_urlsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='note',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
